### ISSUE TITLE
readme on npm has errors

### ISSUE THREAD

**Issue by ungoldman** [finnp/cliclopts#5]
Hello @finnp! I like this module :)

I copied some stuff from the readme on https://www.npmjs.com/package/cliclopts and ran into some errors... looks like they've already been fixed here a few months ago, but not released yet.

https://github.com/finnp/cliclopts/compare/0627952a06b452d385df3ba8bd4288696f977dea...a8be2ce8ac7a51fc5a2ba69cbf1079141f34ab9d (changes since 1.1.0 commit)

Mind doing a push to save future users a headache or two? :grin:

**Comment by finnp** [comment]
Yeah, I just published 1.1.1. Thanks!
